/**
 * db/seed-data/bahasa.mjs — bank soal bahasa dan literasi.
 *
 * Soal bahasa Indonesia mengacu pada kaidah PUEBI dan KBBI. Untuk soal
 * ejaan, pengecohnya adalah bentuk salah yang paling lazim beredar —
 * misalnya "nasehat" atau "praktek" — karena itulah yang perlu diuji,
 * bukan bentuk salah yang tidak pernah ditulis siapa pun.
 */

export const bahasa = [
  {
    id: 'bindo-ejaan',
    title: 'Bahasa Indonesia: Ejaan dan Kosakata',
    category: 'Bahasa Indonesia',
    description: 'Penulisan baku, imbuhan, tanda baca, dan pilihan kata sesuai KBBI.',
    questions: [
      { t: 'Penulisan kata baku yang benar adalah', o: ['nasihat', 'nasehat', 'nasiat', 'nasehad'], a: 0 },
      { t: 'Bentuk baku dari kata "praktek" adalah', o: ['praktik', 'praktek', 'practic', 'praktekk'], a: 0 },
      { t: 'Penulisan yang tepat menurut kaidah adalah', o: ['di rumah', 'dirumah', 'di-rumah', 'dirumahkan'], a: 0, e: 'Kata depan "di" ditulis terpisah dari kata yang mengikutinya.' },
      { t: 'Kata baku dari "apotik" adalah', o: ['apotek', 'apotik', 'apoteker', 'apotekk'], a: 0 },
      { t: 'Imbuhan me- pada kata dasar "sapu" menjadi', o: ['menyapu', 'mensapu', 'menyapuh', 'mesapu'], a: 0 },
      { t: 'Tanda baca yang tepat untuk mengakhiri kalimat tanya adalah', o: ['tanda tanya', 'tanda titik', 'tanda seru', 'tanda koma'], a: 0 },
      { t: 'Kata "kalian" merupakan kata ganti orang', o: ['kedua jamak', 'pertama jamak', 'ketiga tunggal', 'kedua tunggal'], a: 0 },
      { t: 'Sinonim dari kata "cerdas" adalah', o: ['pandai', 'malas', 'lambat', 'ceroboh'], a: 0 },
      { t: 'Antonim dari kata "lapang" adalah', o: ['sempit', 'luas', 'panjang', 'tinggi'], a: 0 },
      { t: 'Penulisan gelar yang benar adalah', o: ['Dr. Sutrisno, M.Pd.', 'Dr Sutrisno M.Pd', 'dr. Sutrisno M,Pd', 'DR. Sutrisno Mpd'], a: 0 },
      { t: 'Kalimat yang menggunakan kata baku adalah', o: ['Ia mengubah rencananya.', 'Ia merubah rencananya.', 'Ia merobah rencananya.', 'Ia mengrubah rencananya.'], a: 0 },
      { t: 'Kata "namun" sebaiknya diletakkan pada', o: ['awal kalimat', 'tengah kalimat', 'akhir kalimat', 'mana saja'], a: 0 },
      { t: 'Bentuk baku dari "resiko" adalah', o: ['risiko', 'resiko', 'risico', 'resikoh'], a: 0 },
      { t: 'Kalimat efektif ditandai dengan', o: ['tidak berlebihan dan jelas maknanya', 'kalimatnya panjang', 'banyak kata asing', 'penuh majas'], a: 0 },
      { t: 'Penulisan angka yang benar dalam kalimat resmi adalah', o: ['Ada 25 peserta yang hadir.', 'Ada duapuluhlima peserta.', 'Ada 25 peserta yg hadir.', 'Ada dua puluh lima peserta yang hadir'], a: 0 },
      { t: 'Kata "sangat sekali" tidak baku karena', o: ['mubazir atau berlebihan', 'terlalu pendek', 'bukan bahasa Indonesia', 'salah ejaan'], a: 0 },
      { t: 'Bentuk baku dari "ijin" adalah', o: ['izin', 'ijin', 'idzin', 'ijzin'], a: 0 },
      { t: 'Kata hubung yang menyatakan sebab adalah', o: ['karena', 'tetapi', 'atau', 'meskipun'], a: 0 },
      { t: 'Penulisan kata depan "ke" yang benar adalah', o: ['ke sekolah', 'kesekolah', 'ke-sekolah', 'kesekolahan'], a: 0 },
      { t: 'Kalimat perintah biasanya diakhiri dengan', o: ['tanda seru', 'tanda tanya', 'tanda titik dua', 'tanda kurung'], a: 0 },
      { t: 'Kata "analisa" bentuk bakunya adalah', o: ['analisis', 'analisa', 'analitis', 'analise'], a: 0 },
      { t: 'Huruf kapital digunakan pada awal', o: ['nama orang dan tempat', 'setiap kata', 'kata sambung', 'akhir kalimat'], a: 0 },
      { t: 'Bentuk baku dari "atlit" adalah', o: ['atlet', 'atlit', 'athlet', 'atlot'], a: 0 },
      { t: 'Kata "yang mana" dalam kalimat formal sebaiknya', o: ['dihindari karena tidak baku', 'selalu digunakan', 'ditulis miring', 'diberi tanda kutip'], a: 0 },
      { t: 'Bentuk baku dari "kwalitas" adalah', o: ['kualitas', 'kwalitas', 'qualitas', 'kwalitet'], a: 0 },
      { t: 'Penulisan tanggal surat resmi yang benar adalah', o: ['12 Agustus 2026', '12 agustus 2026', '12-8-2026', 'Agustus 12, 2026'], a: 0 },
    ],
  },
  {
    id: 'bindo-teks',
    title: 'Bahasa Indonesia: Teks dan Sastra',
    category: 'Bahasa Indonesia',
    description: 'Jenis teks, unsur intrinsik, majas, dan pemahaman bacaan.',
    questions: [
      { t: 'Gagasan utama sebuah paragraf biasanya terdapat pada', o: ['kalimat utama', 'kalimat penjelas', 'kalimat terakhir saja', 'judul'], a: 0 },
      { t: 'Teks yang bertujuan mengajak pembaca melakukan sesuatu disebut teks', o: ['persuasi', 'deskripsi', 'narasi', 'laporan'], a: 0 },
      { t: 'Teks yang menceritakan rangkaian peristiwa secara berurutan disebut teks', o: ['narasi', 'eksposisi', 'argumentasi', 'prosedur'], a: 0 },
      { t: 'Unsur intrinsik cerita yang menunjukkan tempat dan waktu kejadian adalah', o: ['latar', 'tema', 'alur', 'amanat'], a: 0 },
      { t: 'Pesan moral yang ingin disampaikan pengarang disebut', o: ['amanat', 'tema', 'tokoh', 'sudut pandang'], a: 0 },
      { t: 'Majas yang membandingkan dua hal secara langsung tanpa kata pembanding disebut', o: ['metafora', 'simile', 'personifikasi', 'hiperbola'], a: 0 },
      { t: 'Majas yang memberikan sifat manusia pada benda mati disebut', o: ['personifikasi', 'metafora', 'ironi', 'litotes'], a: 0 },
      { t: '"Suaranya menggelegar memecah langit" merupakan majas', o: ['hiperbola', 'litotes', 'eufemisme', 'metonimia'], a: 0 },
      { t: 'Karya sastra berbentuk cerita rekaan panjang disebut', o: ['novel', 'puisi', 'pantun', 'esai'], a: 0 },
      { t: 'Pantun memiliki jumlah baris sebanyak', o: ['empat', 'dua', 'enam', 'delapan'], a: 0 },
      { t: 'Sampiran pada pantun terletak di baris', o: ['pertama dan kedua', 'ketiga dan keempat', 'pertama saja', 'keempat saja'], a: 0 },
      { t: 'Rima akhir pantun umumnya berpola', o: ['a-b-a-b', 'a-a-a-a', 'a-b-b-a', 'bebas'], a: 0 },
      { t: 'Teks yang berisi langkah-langkah melakukan sesuatu disebut teks', o: ['prosedur', 'deskripsi', 'ulasan', 'berita'], a: 0 },
      { t: 'Unsur berita yang menjawab pertanyaan "mengapa" adalah', o: ['why', 'what', 'when', 'who'], a: 0 },
      { t: 'Sudut pandang yang menggunakan kata "aku" disebut sudut pandang', o: ['orang pertama', 'orang kedua', 'orang ketiga', 'campuran'], a: 0 },
      { t: 'Bagian awal cerita yang memperkenalkan tokoh dan latar disebut', o: ['orientasi', 'komplikasi', 'resolusi', 'koda'], a: 0 },
      { t: 'Puisi lama yang berisi nasihat dan terdiri atas dua baris disebut', o: ['gurindam', 'syair', 'pantun', 'seloka'], a: 0 },
      { t: 'Kalimat yang menyatakan pendapat disebut kalimat', o: ['opini', 'fakta', 'perintah', 'tanya'], a: 0 },
      { t: 'Teks yang menilai kelebihan dan kekurangan sebuah karya disebut teks', o: ['ulasan', 'prosedur', 'laporan', 'eksplanasi'], a: 0 },
      { t: 'Konflik dalam cerita mencapai puncaknya pada bagian', o: ['klimaks', 'orientasi', 'resolusi', 'prolog'], a: 0 },
      { t: 'Majas yang menghaluskan ungkapan agar lebih sopan disebut', o: ['eufemisme', 'sarkasme', 'hiperbola', 'repetisi'], a: 0 },
      { t: 'Karya sastra yang ditulis untuk dipentaskan disebut', o: ['drama', 'novel', 'cerpen', 'puisi'], a: 0 },
      { t: 'Ringkasan isi bacaan dengan tetap mempertahankan urutan gagasan disebut', o: ['ikhtisar', 'sinopsis', 'kutipan', 'parafrasa'], a: 0 },
      { t: 'Kata kunci dalam sebuah teks berguna untuk', o: ['menemukan gagasan pokok', 'memperpanjang teks', 'menambah tokoh', 'mengubah alur'], a: 0 },
      { t: 'Teks eksplanasi bertujuan menjelaskan', o: ['proses terjadinya suatu fenomena', 'pendapat penulis', 'cara membuat sesuatu', 'riwayat tokoh'], a: 0 },
      { t: 'Cerita rakyat yang tokohnya binatang disebut', o: ['fabel', 'legenda', 'mite', 'sage'], a: 0 },
    ],
  },
  {
    id: 'english-basic',
    title: 'English: Grammar and Vocabulary',
    category: 'Bahasa Inggris',
    description: 'Tenses, kosakata, preposisi, dan pemahaman kalimat tingkat dasar hingga menengah.',
    questions: [
      { t: 'She ___ to school every morning.', o: ['goes', 'go', 'going', 'gone'], a: 0, e: 'Subjek orang ketiga tunggal pada simple present memakai akhiran -s.' },
      { t: 'The opposite of "expensive" is', o: ['cheap', 'costly', 'rich', 'valuable'], a: 0 },
      { t: 'They ___ football when it started to rain.', o: ['were playing', 'are playing', 'play', 'has played'], a: 0 },
      { t: 'Choose the correct plural form of "child".', o: ['children', 'childs', 'childes', 'childrens'], a: 0 },
      { t: 'I have lived here ___ 2015.', o: ['since', 'for', 'during', 'from'], a: 0, e: '"Since" dipakai untuk titik waktu, "for" untuk rentang waktu.' },
      { t: 'The book ___ by a famous writer.', o: ['was written', 'wrote', 'has wrote', 'is writing'], a: 0 },
      { t: 'What is the past tense of "buy"?', o: ['bought', 'buyed', 'buied', 'boughted'], a: 0 },
      { t: 'She is interested ___ learning Japanese.', o: ['in', 'on', 'at', 'for'], a: 0 },
      { t: 'Which sentence is grammatically correct?', o: ['He does not like coffee.', 'He do not likes coffee.', 'He not like coffee.', 'He does not likes coffee.'], a: 0 },
      { t: 'The synonym of "happy" is', o: ['glad', 'sad', 'angry', 'tired'], a: 0 },
      { t: 'If it rains tomorrow, we ___ the trip.', o: ['will cancel', 'cancelled', 'would cancelled', 'cancels'], a: 0 },
      { t: 'There ___ many students in the hall.', o: ['are', 'is', 'was', 'has'], a: 0 },
      { t: 'Choose the correct comparative form of "good".', o: ['better', 'gooder', 'more good', 'best'], a: 0 },
      { t: 'He has been working here ___ five years.', o: ['for', 'since', 'ago', 'until'], a: 0 },
      { t: 'The meeting was postponed ___ Monday.', o: ['until', 'since', 'during', 'by'], a: 0 },
      { t: 'Which word is a preposition?', o: ['between', 'quickly', 'beautiful', 'run'], a: 0 },
      { t: 'She asked me where I ___ from.', o: ['came', 'come', 'coming', 'comes'], a: 0 },
      { t: 'The antonym of "increase" is', o: ['decrease', 'expand', 'grow', 'rise'], a: 0 },
      { t: 'I would rather ___ at home tonight.', o: ['stay', 'to stay', 'staying', 'stayed'], a: 0 },
      { t: 'Neither John nor his friends ___ coming.', o: ['are', 'is', 'was', 'has'], a: 0, e: 'Kata kerja menyesuaikan subjek terdekat, yaitu "friends".' },
      { t: 'Choose the correct question tag: "You are a teacher, ___?"', o: ["aren't you", 'are you', "isn't it", "don't you"], a: 0 },
      { t: 'The word "generous" means', o: ['willing to give', 'very angry', 'quite shy', 'always late'], a: 0 },
      { t: 'He speaks English ___ than his brother.', o: ['more fluently', 'fluently', 'most fluently', 'fluent'], a: 0 },
      { t: 'Which sentence uses the present perfect correctly?', o: ['I have finished my homework.', 'I have finish my homework.', 'I has finished my homework.', 'I am finished my homework.'], a: 0 },
      { t: 'The plural of "mouse" (the animal) is', o: ['mice', 'mouses', 'mices', 'mouse'], a: 0 },
      { t: 'She apologised ___ being late.', o: ['for', 'of', 'to', 'with'], a: 0 },
    ],
  },
];
