/**
 * db/seed-data/lainnya.mjs — mata pelajaran pelengkap.
 *
 * Bagian budi pekerti sengaja ditulis lintas keyakinan: yang diuji
 * adalah sikap dan nilai yang disepakati bersama, bukan doktrin satu
 * agama tertentu, supaya kuisnya bisa dipakai di kelas mana pun.
 */

export const lainnya = [
  {
    id: 'statistika-peluang',
    title: 'Statistika dan Peluang',
    category: 'Matematika',
    description: 'Penyajian data, ukuran pemusatan, penyebaran, dan peluang kejadian.',
    questions: [
      { t: 'Nilai yang paling sering muncul dalam sekumpulan data disebut', o: ['modus', 'median', 'mean', 'jangkauan'], a: 0 },
      { t: 'Nilai tengah dari data yang telah diurutkan disebut', o: ['median', 'modus', 'rata-rata', 'simpangan'], a: 0 },
      { t: 'Median dari data 3, 5, 7, 9, 11 adalah', o: ['7', '5', '9', '6'], a: 0 },
      { t: 'Rata-rata dari 6, 8, 10, 12 adalah', o: ['9', '8', '10', '11'], a: 0 },
      { t: 'Peluang munculnya angka pada pelemparan satu koin adalah', o: ['1/2', '1/4', '1/3', '1'], a: 0 },
      { t: 'Peluang muncul mata dadu bernilai 4 pada satu dadu adalah', o: ['1/6', '1/4', '1/3', '4/6'], a: 0 },
      { t: 'Jangkauan dari data 4, 9, 15, 22 adalah', o: ['18', '15', '11', '22'], a: 0, e: 'Jangkauan = nilai terbesar dikurangi terkecil.' },
      { t: 'Diagram yang cocok untuk menunjukkan bagian dari keseluruhan adalah', o: ['diagram lingkaran', 'diagram garis', 'diagram batang', 'histogram'], a: 0 },
      { t: 'Peluang kejadian yang pasti terjadi bernilai', o: ['1', '0', '0,5', '100'], a: 0 },
      { t: 'Modus dari data 2, 3, 3, 5, 7, 3, 8 adalah', o: ['3', '5', '2', '7'], a: 0 },
      { t: 'Diagram yang paling tepat menggambarkan perubahan data dari waktu ke waktu adalah', o: ['diagram garis', 'diagram lingkaran', 'diagram batang', 'diagram pohon'], a: 0 },
      { t: 'Jika sebuah dadu dilempar, peluang muncul mata dadu genap adalah', o: ['1/2', '1/3', '1/6', '2/3'], a: 0 },
      { t: 'Data yang diperoleh langsung dari sumbernya disebut data', o: ['primer', 'sekunder', 'tersier', 'kualitatif'], a: 0 },
      { t: 'Median dari data 4, 6, 8, 10 adalah', o: ['7', '6', '8', '9'], a: 0, e: 'Untuk data genap, median adalah rata-rata dua nilai tengah.' },
      { t: 'Banyak cara menyusun 3 buku berbeda dalam satu rak adalah', o: ['6', '3', '9', '12'], a: 0, e: '3! = 3 × 2 × 1 = 6.' },
      { t: 'Peluang kejadian yang mustahil terjadi bernilai', o: ['0', '1', '0,5', '-1'], a: 0 },
      { t: 'Rata-rata nilai 5 siswa adalah 80. Jumlah seluruh nilainya adalah', o: ['400', '80', '160', '320'], a: 0 },
      { t: 'Ukuran yang menunjukkan seberapa jauh data menyebar dari rata-rata adalah', o: ['simpangan baku', 'modus', 'median', 'frekuensi'], a: 0 },
      { t: 'Jika dua koin dilempar bersamaan, banyak kemungkinan hasilnya adalah', o: ['4', '2', '3', '6'], a: 0 },
      { t: 'Data tentang warna favorit termasuk data', o: ['kualitatif', 'kuantitatif', 'kontinu', 'diskret'], a: 0 },
      { t: 'Frekuensi relatif dinyatakan dalam bentuk', o: ['persentase atau pecahan', 'bilangan bulat', 'satuan panjang', 'derajat'], a: 0 },
      { t: 'Pada diagram lingkaran, satu bagian yang mewakili 25% besarnya', o: ['90°', '45°', '120°', '180°'], a: 0 },
      { t: 'Nilai rata-rata sering disebut juga', o: ['mean', 'modus', 'median', 'kuartil'], a: 0 },
      { t: 'Peluang mengambil satu kartu As dari satu set kartu remi 52 lembar adalah', o: ['4/52', '1/52', '13/52', '2/52'], a: 0 },
      { t: 'Sampel adalah', o: ['sebagian dari populasi yang diteliti', 'seluruh populasi', 'hasil akhir penelitian', 'alat ukur'], a: 0 },
      { t: 'Kuartil membagi data terurut menjadi berapa bagian sama banyak?', o: ['empat', 'dua', 'tiga', 'lima'], a: 0 },
    ],
  },
  {
    id: 'seni-budaya',
    title: 'Seni Budaya dan Kearifan Lokal',
    category: 'Seni Budaya',
    description: 'Seni rupa, musik, tari, teater, dan ragam budaya Nusantara.',
    questions: [
      { t: 'Seni yang dinikmati melalui indera penglihatan disebut seni', o: ['rupa', 'musik', 'tari', 'sastra'], a: 0 },
      { t: 'Warna primer terdiri atas', o: ['merah, kuning, biru', 'hijau, jingga, ungu', 'hitam, putih, abu', 'merah, hijau, biru'], a: 0 },
      { t: 'Alat musik tradisional yang dimainkan dengan digoyangkan adalah', o: ['angklung', 'kendang', 'suling', 'rebab'], a: 0 },
      { t: 'Tari Kecak berasal dari daerah', o: ['Bali', 'Jawa Barat', 'Aceh', 'Papua'], a: 0 },
      { t: 'Teknik menggambar dengan titik-titik disebut', o: ['pointilis', 'arsir', 'blok', 'dusel'], a: 0 },
      { t: 'Wayang kulit dimainkan oleh seorang', o: ['dalang', 'sinden', 'niyaga', 'sutradara'], a: 0 },
      { t: 'Tangga nada diatonis mayor memiliki jarak nada', o: ['1-1-½-1-1-1-½', '1-½-1-1-½-1-1', '1-1-1-½-1-1-½', '½-1-1-1-½-1-1'], a: 0 },
      { t: 'Seni membentuk benda tiga dimensi dari tanah liat disebut', o: ['seni keramik', 'seni lukis', 'seni grafis', 'seni kriya kayu'], a: 0 },
      { t: 'Kain tradisional yang dibuat dengan teknik tulis menggunakan malam disebut', o: ['batik', 'tenun', 'songket', 'ulos'], a: 0 },
      { t: 'Unsur utama dalam seni tari adalah', o: ['gerak', 'suara', 'warna', 'garis'], a: 0 },
      { t: 'Alat musik gamelan yang berfungsi mengatur tempo adalah', o: ['kendang', 'gong', 'saron', 'bonang'], a: 0 },
      { t: 'Lagu daerah "Bungong Jeumpa" berasal dari', o: ['Aceh', 'Sumatra Utara', 'Riau', 'Jambi'], a: 0 },
      { t: 'Perpaduan warna yang berdekatan pada lingkaran warna disebut', o: ['analogus', 'komplementer', 'monokrom', 'triadik'], a: 0 },
      { t: 'Seni pertunjukan yang memadukan dialog, gerak, dan cerita disebut', o: ['teater', 'pantomim', 'orkestra', 'kaligrafi'], a: 0 },
      { t: 'Rumah Gadang merupakan rumah adat dari', o: ['Sumatra Barat', 'Sumatra Utara', 'Jawa Timur', 'Bali'], a: 0 },
      { t: 'Tempo lagu yang berarti cepat adalah', o: ['allegro', 'adagio', 'largo', 'andante'], a: 0 },
      { t: 'Seni rupa yang memiliki panjang, lebar, dan tinggi disebut karya', o: ['tiga dimensi', 'dua dimensi', 'satu dimensi', 'empat dimensi'], a: 0 },
      { t: 'Alat musik tiup tradisional dari bambu adalah', o: ['suling', 'kecapi', 'gong', 'tifa'], a: 0 },
      { t: 'Tari Piring berasal dari daerah', o: ['Sumatra Barat', 'Kalimantan Timur', 'Maluku', 'Bali'], a: 0 },
      { t: 'Lagu "Rasa Sayange" berasal dari', o: ['Maluku', 'Papua', 'Sulawesi Utara', 'Nusa Tenggara'], a: 0 },
      { t: 'Menyanyi dengan banyak suara berbeda yang berpadu disebut', o: ['paduan suara', 'solo', 'akapela tunggal', 'resitasi'], a: 0 },
      { t: 'Alat musik Tifa berasal dari daerah', o: ['Papua', 'Jawa', 'Sumatra', 'Kalimantan'], a: 0 },
      { t: 'Karya seni yang dibuat untuk memenuhi kebutuhan sehari-hari disebut seni', o: ['terapan', 'murni', 'abstrak', 'kontemporer'], a: 0 },
      { t: 'Notasi angka pada musik menggunakan simbol', o: ['1 sampai 7', 'A sampai G', 'do sampai la', 'I sampai V'], a: 0 },
      { t: 'Ragam hias yang mengambil bentuk tumbuhan disebut motif', o: ['flora', 'fauna', 'geometris', 'figuratif'], a: 0 },
      { t: 'Pertunjukan Reog berasal dari kota', o: ['Ponorogo', 'Malang', 'Solo', 'Cirebon'], a: 0 },
    ],
  },
  {
    id: 'pjok-kesehatan',
    title: 'Olahraga dan Kesehatan',
    category: 'Olahraga',
    description: 'Aturan cabang olahraga, kebugaran jasmani, gizi, dan pertolongan pertama.',
    questions: [
      { t: 'Jumlah pemain bola voli dalam satu regu di lapangan adalah', o: ['6', '5', '7', '11'], a: 0 },
      { t: 'Induk organisasi sepak bola dunia adalah', o: ['FIFA', 'IOC', 'FIBA', 'IAAF'], a: 0 },
      { t: 'Gerakan mendorong bola ke atas dengan dua tangan dalam voli disebut', o: ['passing atas', 'passing bawah', 'smash', 'blok'], a: 0 },
      { t: 'Lama satu babak pertandingan sepak bola adalah', o: ['45 menit', '30 menit', '40 menit', '60 menit'], a: 0 },
      { t: 'Nomor lari jarak pendek dalam atletik adalah', o: ['100 meter', '5.000 meter', '10.000 meter', 'maraton'], a: 0 },
      { t: 'Gaya renang yang dilakukan dengan posisi telentang adalah', o: ['gaya punggung', 'gaya bebas', 'gaya dada', 'gaya kupu-kupu'], a: 0 },
      { t: 'Pemanasan sebelum berolahraga bertujuan untuk', o: ['mengurangi risiko cedera', 'menambah berat badan', 'mempercepat lapar', 'menurunkan suhu tubuh'], a: 0 },
      { t: 'Zat gizi yang menjadi sumber tenaga utama tubuh adalah', o: ['karbohidrat', 'vitamin', 'mineral', 'air'], a: 0 },
      { t: 'Jumlah pemain bola basket dalam satu regu di lapangan adalah', o: ['5', '6', '7', '11'], a: 0 },
      { t: 'Induk organisasi bulu tangkis Indonesia adalah', o: ['PBSI', 'PSSI', 'PBVSI', 'PERBASI'], a: 0 },
      { t: 'Kemampuan tubuh melakukan aktivitas tanpa mudah lelah disebut', o: ['daya tahan', 'kelenturan', 'kecepatan', 'kekuatan'], a: 0 },
      { t: 'Latihan yang paling tepat untuk melatih kelenturan adalah', o: ['peregangan', 'angkat beban', 'lari cepat', 'lompat tinggi'], a: 0 },
      { t: 'Jumlah set maksimal dalam pertandingan bulu tangkis adalah', o: ['3', '2', '5', '4'], a: 0 },
      { t: 'Vitamin yang diperoleh tubuh dari sinar matahari pagi adalah', o: ['vitamin D', 'vitamin A', 'vitamin C', 'vitamin K'], a: 0 },
      { t: 'Tindakan pertama pada cedera memar ringan adalah', o: ['mengompres dengan es', 'memijat kuat', 'mengoles minyak panas', 'membiarkannya'], a: 0 },
      { t: 'Olahraga yang termasuk cabang atletik adalah', o: ['lompat jauh', 'sepak bola', 'renang', 'basket'], a: 0 },
      { t: 'Gizi seimbang menurut pedoman terbaru digambarkan dengan', o: ['tumpeng gizi seimbang', 'empat sehat lima sempurna', 'piramida makanan lama', 'segitiga emas'], a: 0 },
      { t: 'Denyut nadi normal orang dewasa saat istirahat berkisar', o: ['60–100 per menit', '20–40 per menit', '120–160 per menit', '150–200 per menit'], a: 0 },
      { t: 'Kartu merah dalam sepak bola berarti pemain', o: ['dikeluarkan dari pertandingan', 'diberi peringatan', 'mendapat tendangan bebas', 'diganti pemain lain'], a: 0 },
      { t: 'Start yang digunakan pada lari jarak pendek adalah', o: ['start jongkok', 'start berdiri', 'start melayang', 'start duduk'], a: 0 },
      { t: 'Air putih sebaiknya diminum orang dewasa sekitar', o: ['delapan gelas sehari', 'dua gelas sehari', 'satu gelas sehari', 'dua puluh gelas sehari'], a: 0 },
      { t: 'Cabang olahraga yang menggunakan matras dan gerakan guling disebut', o: ['senam lantai', 'atletik', 'renang', 'panahan'], a: 0 },
      { t: 'Tinggi net bola voli untuk putra adalah', o: ['2,43 meter', '2,24 meter', '2,50 meter', '2,10 meter'], a: 0 },
      { t: 'Istirahat yang cukup bagi remaja setiap malam adalah', o: ['delapan sampai sembilan jam', 'tiga jam', 'lima jam', 'dua belas jam'], a: 0 },
      { t: 'Penyakit yang disebabkan kurangnya asupan zat besi adalah', o: ['anemia', 'diabetes', 'asma', 'maag'], a: 0 },
      { t: 'Olahraga yang baik dilakukan minimal berapa kali seminggu?', o: ['tiga kali', 'sekali', 'sebulan sekali', 'setiap jam'], a: 0 },
    ],
  },
  {
    id: 'budi-pekerti',
    title: 'Budi Pekerti dan Karakter',
    category: 'Karakter',
    description: 'Nilai kejujuran, tanggung jawab, empati, kerja sama, dan etika sehari-hari.',
    questions: [
      { t: 'Mengakui kesalahan yang telah diperbuat merupakan wujud sikap', o: ['jujur dan bertanggung jawab', 'penakut', 'lemah', 'ragu-ragu'], a: 0 },
      { t: 'Menolong teman yang kesulitan tanpa mengharap imbalan disebut', o: ['ikhlas', 'pamrih', 'terpaksa', 'sombong'], a: 0 },
      { t: 'Sikap menghargai pendapat orang lain saat berdiskusi menunjukkan', o: ['toleransi', 'egoisme', 'apatis', 'keras kepala'], a: 0 },
      { t: 'Datang tepat waktu ke sekolah mencerminkan sikap', o: ['disiplin', 'boros', 'malas', 'ceroboh'], a: 0 },
      { t: 'Menyontek saat ujian bertentangan dengan nilai', o: ['kejujuran', 'kerja sama', 'keberanian', 'kreativitas'], a: 0 },
      { t: 'Kemampuan merasakan apa yang dirasakan orang lain disebut', o: ['empati', 'apatis', 'antipati', 'simpati semu'], a: 0 },
      { t: 'Menjaga kebersihan lingkungan sekolah merupakan tanggung jawab', o: ['seluruh warga sekolah', 'petugas kebersihan saja', 'kepala sekolah', 'siswa kelas akhir'], a: 0 },
      { t: 'Sikap yang tepat ketika berbeda pendapat dengan teman adalah', o: ['mendengarkan dan mencari titik temu', 'memaksakan kehendak', 'memutus pertemanan', 'diam saja selamanya'], a: 0 },
      { t: 'Mengembalikan barang temuan kepada pemiliknya mencerminkan sikap', o: ['amanah', 'boros', 'sombong', 'acuh'], a: 0 },
      { t: 'Bekerja sama menyelesaikan tugas kelompok disebut', o: ['gotong royong', 'individualisme', 'kompetisi', 'persaingan'], a: 0 },
      { t: 'Menggunakan uang saku sesuai kebutuhan menunjukkan sikap', o: ['hemat', 'kikir', 'boros', 'serakah'], a: 0 },
      { t: 'Sikap yang perlu ditunjukkan kepada orang yang lebih tua adalah', o: ['hormat dan santun', 'acuh tak acuh', 'menggurui', 'meremehkan'], a: 0 },
      { t: 'Berani menyampaikan kebenaran meski tidak populer disebut', o: ['integritas', 'nekat', 'sombong', 'keras kepala'], a: 0 },
      { t: 'Menepati janji merupakan bentuk', o: ['tanggung jawab', 'kebetulan', 'formalitas', 'paksaan'], a: 0 },
      { t: 'Sikap yang benar saat melihat teman dirundung adalah', o: ['membela dan melapor kepada guru', 'ikut menertawakan', 'merekam dan menyebarkan', 'diam saja'], a: 0 },
      { t: 'Menghargai perbedaan agama di sekolah merupakan pengamalan', o: ['sila pertama Pancasila', 'sila kedua saja', 'aturan sekolah', 'kebiasaan lokal'], a: 0 },
      { t: 'Rasa syukur dapat diwujudkan dengan', o: ['memanfaatkan yang dimiliki sebaik-baiknya', 'mengeluh terus', 'membandingkan diri', 'menuntut lebih'], a: 0 },
      { t: 'Sikap sportif dalam pertandingan berarti', o: ['menerima hasil dengan lapang dada', 'menang dengan segala cara', 'menyalahkan wasit', 'menghindari lawan kuat'], a: 0 },
      { t: 'Meminta izin sebelum meminjam barang teman menunjukkan', o: ['sopan santun', 'keraguan', 'ketakutan', 'kelemahan'], a: 0 },
      { t: 'Menyelesaikan pekerjaan rumah sendiri melatih', o: ['kemandirian', 'ketergantungan', 'kemalasan', 'kecurangan'], a: 0 },
      { t: 'Sikap yang tepat ketika menerima kritik adalah', o: ['mendengarkan dan memperbaiki diri', 'marah', 'membalas', 'menghindar'], a: 0 },
      { t: 'Membuang sampah pada tempatnya termasuk bentuk', o: ['peduli lingkungan', 'gengsi', 'kewajiban orang lain', 'kebiasaan buruk'], a: 0 },
      { t: 'Kerja keras yang disertai doa dan kesabaran disebut', o: ['ikhtiar', 'pasrah', 'nekat', 'untung-untungan'], a: 0 },
      { t: 'Menjaga rahasia teman yang dipercayakan kepada kita menunjukkan sikap', o: ['dapat dipercaya', 'tertutup', 'penakut', 'pendiam'], a: 0 },
      { t: 'Antre dengan tertib mencerminkan sikap', o: ['menghargai hak orang lain', 'lambat', 'penurut', 'pemalu'], a: 0 },
      { t: 'Sikap terbaik ketika gagal mencapai target adalah', o: ['mengevaluasi lalu mencoba lagi', 'menyerah', 'menyalahkan orang lain', 'berhenti berusaha'], a: 0 },
    ],
  },
  {
    id: 'astronomi-bumi',
    title: 'Bumi dan Antariksa',
    category: 'Sains',
    description: 'Tata surya, gerak bumi, gerhana, atmosfer, dan penjelajahan antariksa.',
    questions: [
      { t: 'Planet yang paling dekat dengan matahari adalah', o: ['Merkurius', 'Venus', 'Bumi', 'Mars'], a: 0 },
      { t: 'Bumi berputar pada porosnya dalam waktu sekitar', o: ['24 jam', '12 jam', '365 hari', '30 hari'], a: 0 },
      { t: 'Gerakan bumi mengelilingi matahari disebut', o: ['revolusi', 'rotasi', 'presesi', 'nutasi'], a: 0 },
      { t: 'Gerhana matahari terjadi ketika', o: ['bulan berada di antara matahari dan bumi', 'bumi di antara matahari dan bulan', 'matahari di antara bumi dan bulan', 'bulan di belakang bumi'], a: 0 },
      { t: 'Planet yang dikenal sebagai planet merah adalah', o: ['Mars', 'Jupiter', 'Venus', 'Merkurius'], a: 0 },
      { t: 'Bintang terdekat dengan bumi adalah', o: ['matahari', 'Proxima Centauri', 'Sirius', 'Polaris'], a: 0 },
      { t: 'Galaksi tempat tata surya kita berada bernama', o: ['Bima Sakti', 'Andromeda', 'Triangulum', 'Sombrero'], a: 0 },
      { t: 'Planet yang memiliki cincin paling jelas terlihat adalah', o: ['Saturnus', 'Jupiter', 'Uranus', 'Neptunus'], a: 0 },
      { t: 'Benda langit yang mengelilingi planet disebut', o: ['satelit', 'komet', 'asteroid', 'meteor'], a: 0 },
      { t: 'Meteor yang sampai ke permukaan bumi disebut', o: ['meteorit', 'meteoroid', 'komet', 'asteroid'], a: 0 },
      { t: 'Perbedaan musim di bumi terjadi karena', o: ['kemiringan sumbu bumi saat berevolusi', 'jarak ke matahari berubah drastis', 'rotasi bumi melambat', 'gerak bulan'], a: 0 },
      { t: 'Manusia pertama yang mendarat di bulan adalah', o: ['Neil Armstrong', 'Yuri Gagarin', 'Buzz Aldrin', 'John Glenn'], a: 0 },
      { t: 'Lapisan bumi paling luar tempat kita tinggal disebut', o: ['kerak', 'mantel', 'inti luar', 'inti dalam'], a: 0 },
      { t: 'Sabuk asteroid terletak di antara planet', o: ['Mars dan Jupiter', 'Bumi dan Mars', 'Jupiter dan Saturnus', 'Venus dan Bumi'], a: 0 },
      { t: 'Jumlah planet dalam tata surya saat ini adalah', o: ['delapan', 'sembilan', 'tujuh', 'sepuluh'], a: 0, e: 'Pluto dikelompokkan ulang sebagai planet kerdil sejak 2006.' },
      { t: 'Ekor komet selalu mengarah', o: ['menjauhi matahari', 'mendekati matahari', 'ke bumi', 'ke atas'], a: 0 },
      { t: 'Satu tahun cahaya adalah satuan untuk mengukur', o: ['jarak', 'waktu', 'massa', 'suhu'], a: 0 },
      { t: 'Pasang surut air laut terutama dipengaruhi oleh', o: ['gravitasi bulan', 'angin', 'suhu udara', 'rotasi awan'], a: 0 },
      { t: 'Gerhana bulan terjadi saat', o: ['bumi berada di antara matahari dan bulan', 'bulan di antara bumi dan matahari', 'bulan purnama selalu', 'matahari tertutup awan'], a: 0 },
      { t: 'Planet terjauh dari matahari saat ini adalah', o: ['Neptunus', 'Uranus', 'Pluto', 'Saturnus'], a: 0 },
      { t: 'Alat untuk mengamati benda langit yang jauh adalah', o: ['teleskop', 'mikroskop', 'periskop', 'stetoskop'], a: 0 },
      { t: 'Matahari tergolong bintang berjenis', o: ['katai kuning', 'raksasa merah', 'katai putih', 'bintang neutron'], a: 0 },
      { t: 'Lapisan atmosfer tempat terjadinya cuaca adalah', o: ['troposfer', 'stratosfer', 'mesosfer', 'termosfer'], a: 0 },
      { t: 'Satelit buatan pertama yang diluncurkan manusia bernama', o: ['Sputnik 1', 'Apollo 11', 'Voyager 1', 'Hubble'], a: 0 },
      { t: 'Cahaya matahari sampai ke bumi dalam waktu sekitar', o: ['8 menit', '8 detik', '8 jam', '1 menit'], a: 0 },
      { t: 'Aurora terjadi karena interaksi partikel matahari dengan', o: ['medan magnet bumi', 'awan hujan', 'lapisan ozon', 'permukaan laut'], a: 0 },
    ],
  },
];
