/**
 * db/seed-data/sains.mjs — bank soal rumpun sains.
 *
 * Isi tiap soal ditulis untuk dipakai di kelas, bukan sekadar mengisi
 * baris. Pilihan pengecohnya diambil dari kesalahan yang benar-benar
 * sering muncul — misalnya tertukarnya massa jenis dengan berat, atau
 * salah membaca tanda pada muatan ion — supaya jawaban benar tidak bisa
 * ditebak hanya dengan melihat mana yang paling berbeda sendiri.
 *
 * Bentuk data:
 *   t  teks soal
 *   o  pilihan jawaban
 *   a  indeks jawaban benar
 *   e  penjelasan singkat (opsional)
 */

export const sains = [
  {
    id: 'mtk-dasar',
    title: 'Matematika Dasar: Bilangan dan Operasi',
    category: 'Matematika',
    description: 'Latihan operasi hitung, pecahan, persen, dan pola bilangan untuk tingkat menengah.',
    questions: [
      { t: 'Hasil dari 17 × 23 adalah', o: ['391', '381', '401', '371'], a: 0, e: '17 × 23 = 17 × 20 + 17 × 3 = 340 + 51 = 391.' },
      { t: 'Bentuk sederhana dari pecahan 42/56 adalah', o: ['3/4', '2/3', '6/7', '7/8'], a: 0, e: 'Faktor persekutuan terbesar 42 dan 56 adalah 14. 42÷14=3, 56÷14=4.' },
      { t: 'Berapa 15% dari 240?', o: ['36', '32', '40', '24'], a: 0, e: '10% = 24, 5% = 12, jumlahnya 36.' },
      { t: 'Nilai x yang memenuhi 3x + 7 = 25 adalah', o: ['6', '5', '8', '9'], a: 0, e: '3x = 18, sehingga x = 6.' },
      { t: 'Suku berikutnya pada barisan 2, 6, 12, 20, 30, ... adalah', o: ['42', '40', '38', '44'], a: 0, e: 'Selisihnya bertambah 2 tiap langkah: 4, 6, 8, 10, lalu 12. Jadi 30 + 12 = 42.' },
      { t: 'Kelipatan persekutuan terkecil dari 12 dan 18 adalah', o: ['36', '54', '72', '24'], a: 0, e: '12 = 2²×3, 18 = 2×3². KPK = 2²×3² = 36.' },
      { t: 'Hasil dari (-8) + 15 − (−3) adalah', o: ['10', '4', '20', '-26'], a: 0, e: 'Mengurangi bilangan negatif sama dengan menambah: −8 + 15 + 3 = 10.' },
      { t: 'Akar kuadrat dari 169 adalah', o: ['13', '12', '14', '17'], a: 0, e: '13 × 13 = 169.' },
      { t: 'Jika 5 pekerja menyelesaikan tugas dalam 12 hari, berapa hari yang dibutuhkan 6 pekerja dengan kecepatan sama?', o: ['10 hari', '14 hari', '9 hari', '15 hari'], a: 0, e: 'Perbandingan berbalik nilai: 5 × 12 = 6 × n, maka n = 10.' },
      { t: 'Rata-rata dari 4, 8, 15, 16, 23, 42 adalah', o: ['18', '16', '20', '17'], a: 0, e: 'Jumlahnya 108, dibagi 6 hasilnya 18.' },
      { t: 'Bentuk desimal dari 3/8 adalah', o: ['0,375', '0,325', '0,385', '0,275'], a: 0, e: '3 dibagi 8 sama dengan 0,375.' },
      { t: 'Hasil dari 2⁵ × 2³ adalah', o: ['256', '64', '128', '512'], a: 0, e: 'Pangkat dijumlahkan: 2⁸ = 256.' },
      { t: 'Sebuah barang dijual Rp90.000 setelah diskon 25%. Harga sebelum diskon adalah', o: ['Rp120.000', 'Rp112.500', 'Rp115.000', 'Rp135.000'], a: 0, e: '90.000 adalah 75% dari harga awal. 90.000 ÷ 0,75 = 120.000.' },
      { t: 'Faktor persekutuan terbesar dari 48 dan 60 adalah', o: ['12', '6', '24', '8'], a: 0, e: '48 = 2⁴×3, 60 = 2²×3×5. FPB = 2²×3 = 12.' },
      { t: 'Nilai dari 0,25 + 1/2 + 25% adalah', o: ['1', '0,75', '1,25', '0,5'], a: 0, e: 'Ketiganya berturut-turut 0,25 + 0,5 + 0,25 = 1.' },
      { t: 'Jika a = 3 dan b = −2, nilai a² − 2ab adalah', o: ['21', '-3', '9', '15'], a: 0, e: '9 − 2(3)(−2) = 9 + 12 = 21.' },
      { t: 'Bilangan prima terkecil yang lebih besar dari 50 adalah', o: ['53', '51', '52', '55'], a: 0, e: '51 habis dibagi 3, 52 genap, 55 habis dibagi 5. Jadi 53.' },
      { t: 'Hasil dari 144 : 12 × 3 adalah', o: ['36', '4', '48', '12'], a: 0, e: 'Bagi dan kali sederajat, dikerjakan dari kiri: 12 × 3 = 36.' },
      { t: 'Perbandingan 3 : 5 senilai dengan', o: ['12 : 20', '9 : 12', '6 : 8', '15 : 20'], a: 0, e: 'Keduanya dikalikan 4 menghasilkan 12 : 20.' },
      { t: 'Nilai dari 1/2 + 1/3 adalah', o: ['5/6', '2/5', '1/6', '2/6'], a: 0, e: 'Disamakan penyebutnya: 3/6 + 2/6 = 5/6.' },
      { t: 'Sebuah bilangan dikurangi 12 lalu dikali 3 menghasilkan 45. Bilangan itu adalah', o: ['27', '23', '19', '31'], a: 0, e: '45 ÷ 3 = 15, lalu 15 + 12 = 27.' },
      { t: 'Hasil dari (−3)³ adalah', o: ['-27', '27', '-9', '9'], a: 0, e: 'Pangkat ganjil mempertahankan tanda negatif.' },
      { t: 'Persentase 18 dari 72 adalah', o: ['25%', '20%', '30%', '35%'], a: 0, e: '18/72 = 0,25 atau 25%.' },
      { t: 'Nilai x pada 2(x − 4) = 10 adalah', o: ['9', '7', '3', '11'], a: 0, e: 'x − 4 = 5, sehingga x = 9.' },
      { t: 'Jumlah bilangan bulat dari 1 sampai 20 adalah', o: ['210', '200', '190', '220'], a: 0, e: 'Rumus n(n+1)/2 = 20 × 21 / 2 = 210.' },
      { t: 'Bentuk baku dari 0,00045 adalah', o: ['4,5 × 10⁻⁴', '4,5 × 10⁻³', '45 × 10⁻⁵', '4,5 × 10⁻⁵'], a: 0, e: 'Koma digeser empat langkah ke kanan.' },
    ],
  },
  {
    id: 'mtk-geometri',
    title: 'Geometri dan Pengukuran',
    category: 'Matematika',
    description: 'Bangun datar, bangun ruang, keliling, luas, dan volume.',
    questions: [
      { t: 'Luas lingkaran dengan jari-jari 7 cm adalah (π = 22/7)', o: ['154 cm²', '44 cm²', '49 cm²', '308 cm²'], a: 0, e: 'L = πr² = 22/7 × 49 = 154.' },
      { t: 'Keliling persegi panjang berukuran 12 cm × 8 cm adalah', o: ['40 cm', '96 cm', '20 cm', '48 cm'], a: 0, e: 'K = 2(12 + 8) = 40 cm.' },
      { t: 'Volume kubus dengan rusuk 5 cm adalah', o: ['125 cm³', '150 cm³', '25 cm³', '100 cm³'], a: 0, e: 'V = s³ = 125.' },
      { t: 'Jumlah sudut dalam sebuah segitiga adalah', o: ['180°', '360°', '90°', '270°'], a: 0, e: 'Berlaku untuk semua jenis segitiga.' },
      { t: 'Sisi miring segitiga siku-siku dengan sisi 6 cm dan 8 cm adalah', o: ['10 cm', '12 cm', '14 cm', '9 cm'], a: 0, e: 'Teorema Pythagoras: √(36+64) = √100 = 10.' },
      { t: 'Luas segitiga dengan alas 14 cm dan tinggi 9 cm adalah', o: ['63 cm²', '126 cm²', '23 cm²', '42 cm²'], a: 0, e: 'L = ½ × 14 × 9 = 63.' },
      { t: 'Banyak rusuk pada balok adalah', o: ['12', '8', '6', '10'], a: 0, e: 'Balok punya 12 rusuk, 8 titik sudut, dan 6 sisi.' },
      { t: 'Volume tabung berjari-jari 7 cm dan tinggi 10 cm adalah (π = 22/7)', o: ['1.540 cm³', '440 cm³', '770 cm³', '2.200 cm³'], a: 0, e: 'V = πr²t = 154 × 10 = 1.540.' },
      { t: 'Sudut yang besarnya lebih dari 90° dan kurang dari 180° disebut sudut', o: ['tumpul', 'lancip', 'siku-siku', 'lurus'], a: 0 },
      { t: 'Luas trapesium dengan sisi sejajar 8 cm dan 12 cm serta tinggi 6 cm adalah', o: ['60 cm²', '120 cm²', '48 cm²', '96 cm²'], a: 0, e: 'L = ½ × (8+12) × 6 = 60.' },
      { t: 'Bangun ruang yang semua sisinya berbentuk segitiga adalah', o: ['limas segitiga', 'prisma segitiga', 'kerucut', 'balok'], a: 0 },
      { t: 'Keliling lingkaran berdiameter 14 cm adalah (π = 22/7)', o: ['44 cm', '154 cm', '88 cm', '22 cm'], a: 0, e: 'K = πd = 22/7 × 14 = 44.' },
      { t: 'Luas belah ketupat dengan diagonal 10 cm dan 24 cm adalah', o: ['120 cm²', '240 cm²', '34 cm²', '60 cm²'], a: 0, e: 'L = ½ × d₁ × d₂ = 120.' },
      { t: 'Banyak sisi pada prisma segi lima adalah', o: ['7', '5', '10', '6'], a: 0, e: 'Dua sisi alas dan tutup, ditambah lima sisi tegak.' },
      { t: 'Satu meter persegi sama dengan berapa sentimeter persegi?', o: ['10.000', '100', '1.000', '100.000'], a: 0, e: '100 cm × 100 cm = 10.000 cm².' },
      { t: 'Volume kerucut berjari-jari 3 cm dan tinggi 4 cm adalah (π = 3,14)', o: ['37,68 cm³', '113,04 cm³', '12,56 cm³', '75,36 cm³'], a: 0, e: 'V = ⅓πr²t = ⅓ × 3,14 × 9 × 4.' },
      { t: 'Dua garis yang tidak pernah berpotongan meski diperpanjang disebut', o: ['sejajar', 'tegak lurus', 'berimpit', 'bersilangan'], a: 0 },
      { t: 'Luas permukaan kubus dengan rusuk 4 cm adalah', o: ['96 cm²', '64 cm²', '16 cm²', '48 cm²'], a: 0, e: 'L = 6s² = 6 × 16 = 96.' },
      { t: 'Segitiga dengan ketiga sisi sama panjang disebut segitiga', o: ['sama sisi', 'sama kaki', 'siku-siku', 'sembarang'], a: 0 },
      { t: 'Satu liter setara dengan', o: ['1.000 cm³', '100 cm³', '10 cm³', '10.000 cm³'], a: 0 },
      { t: 'Jumlah sudut dalam segi empat adalah', o: ['360°', '180°', '540°', '720°'], a: 0 },
      { t: 'Luas jajar genjang dengan alas 15 cm dan tinggi 8 cm adalah', o: ['120 cm²', '60 cm²', '23 cm²', '46 cm²'], a: 0 },
      { t: 'Banyak titik sudut pada limas segi empat adalah', o: ['5', '4', '8', '6'], a: 0, e: 'Empat di alas dan satu di puncak.' },
      { t: 'Skala 1 : 500 pada denah berarti 1 cm di gambar mewakili', o: ['5 meter', '500 meter', '50 meter', '0,5 meter'], a: 0, e: '500 cm sama dengan 5 meter.' },
      { t: 'Volume bola berjari-jari 3 cm adalah (π = 3,14)', o: ['113,04 cm³', '37,68 cm³', '28,26 cm³', '226,08 cm³'], a: 0, e: 'V = 4/3 πr³.' },
      { t: 'Bangun datar yang memiliki tepat satu sumbu simetri adalah', o: ['segitiga sama kaki', 'persegi', 'lingkaran', 'persegi panjang'], a: 0 },
    ],
  },
  {
    id: 'fisika-dasar',
    title: 'Fisika: Gerak, Gaya, dan Energi',
    category: 'Fisika',
    description: 'Konsep dasar mekanika, energi, dan pengukuran besaran fisika.',
    questions: [
      { t: 'Satuan gaya dalam Sistem Internasional adalah', o: ['newton', 'joule', 'watt', 'pascal'], a: 0 },
      { t: 'Kecepatan mobil yang menempuh 180 km dalam 3 jam adalah', o: ['60 km/jam', '54 km/jam', '600 km/jam', '45 km/jam'], a: 0, e: 'v = s/t = 180/3.' },
      { t: 'Hukum I Newton menyatakan bahwa benda akan', o: ['mempertahankan keadaan geraknya bila tidak ada gaya luar', 'selalu bergerak lurus', 'selalu berhenti', 'bergerak makin cepat'], a: 0 },
      { t: 'Energi yang dimiliki benda karena kedudukannya disebut energi', o: ['potensial', 'kinetik', 'kalor', 'listrik'], a: 0 },
      { t: 'Besaran yang memiliki nilai dan arah disebut besaran', o: ['vektor', 'skalar', 'pokok', 'turunan'], a: 0 },
      { t: 'Percepatan gravitasi bumi mendekati', o: ['9,8 m/s²', '9,8 km/s²', '98 m/s²', '0,98 m/s²'], a: 0 },
      { t: 'Alat untuk mengukur suhu adalah', o: ['termometer', 'barometer', 'dinamometer', 'anemometer'], a: 0 },
      { t: 'Usaha bernilai nol jika gaya yang bekerja', o: ['tegak lurus terhadap arah perpindahan', 'searah perpindahan', 'sangat besar', 'berlawanan arah'], a: 0, e: 'W = F·s·cos θ, dan cos 90° = 0.' },
      { t: 'Massa jenis air murni adalah', o: ['1.000 kg/m³', '100 kg/m³', '10 kg/m³', '10.000 kg/m³'], a: 0 },
      { t: 'Benda yang dijatuhkan bebas mengalami gerak', o: ['lurus berubah beraturan', 'lurus beraturan', 'melingkar', 'parabola'], a: 0 },
      { t: 'Satuan daya adalah', o: ['watt', 'joule', 'newton', 'volt'], a: 0 },
      { t: 'Bunyi tidak dapat merambat melalui', o: ['ruang hampa', 'udara', 'air', 'besi'], a: 0, e: 'Bunyi memerlukan medium perantara.' },
      { t: 'Cermin yang selalu menghasilkan bayangan maya, tegak, dan diperkecil adalah cermin', o: ['cembung', 'cekung', 'datar', 'ganda'], a: 0 },
      { t: 'Energi kinetik benda bermassa 2 kg yang bergerak 3 m/s adalah', o: ['9 joule', '6 joule', '18 joule', '3 joule'], a: 0, e: 'Ek = ½mv² = ½ × 2 × 9 = 9.' },
      { t: 'Perpindahan kalor tanpa disertai perpindahan zat perantaranya disebut', o: ['konduksi', 'konveksi', 'radiasi', 'evaporasi'], a: 0 },
      { t: 'Tekanan pada zat cair bertambah seiring bertambahnya', o: ['kedalaman', 'lebar wadah', 'warna zat', 'bentuk wadah'], a: 0 },
      { t: 'Alat yang mengubah energi listrik menjadi energi gerak adalah', o: ['motor listrik', 'generator', 'dinamo', 'trafo'], a: 0 },
      { t: 'Satuan hambatan listrik adalah', o: ['ohm', 'ampere', 'volt', 'coulomb'], a: 0 },
      { t: 'Menurut hukum Ohm, kuat arus berbanding lurus dengan', o: ['tegangan', 'hambatan', 'daya', 'waktu'], a: 0 },
      { t: 'Peristiwa pembelokan cahaya saat melewati dua medium berbeda disebut', o: ['pembiasan', 'pemantulan', 'difraksi', 'polarisasi'], a: 0 },
      { t: 'Sebuah benda bermassa 5 kg berada 4 meter di atas tanah. Energi potensialnya (g = 10 m/s²) adalah', o: ['200 joule', '20 joule', '50 joule', '2.000 joule'], a: 0, e: 'Ep = mgh = 5 × 10 × 4.' },
      { t: 'Frekuensi gelombang dengan periode 0,2 sekon adalah', o: ['5 Hz', '0,2 Hz', '20 Hz', '2 Hz'], a: 0, e: 'f = 1/T.' },
      { t: 'Besaran pokok dalam fisika berjumlah', o: ['tujuh', 'lima', 'tiga', 'sembilan'], a: 0 },
      { t: 'Gaya gesek selalu bekerja', o: ['berlawanan arah dengan gerak benda', 'searah gerak benda', 'tegak lurus gerak', 'ke atas'], a: 0 },
      { t: 'Pesawat sederhana yang bekerja berdasarkan prinsip tuas adalah', o: ['gunting', 'katrol tetap', 'bidang miring', 'roda berporos'], a: 0 },
      { t: 'Cahaya merambat dengan kecepatan mendekati', o: ['300.000 km/detik', '300 km/detik', '3.000 km/detik', '30.000 km/detik'], a: 0 },
    ],
  },
  {
    id: 'kimia-dasar',
    title: 'Kimia: Materi, Unsur, dan Reaksi',
    category: 'Kimia',
    description: 'Struktur atom, tabel periodik, ikatan kimia, dan reaksi sederhana.',
    questions: [
      { t: 'Lambang kimia untuk emas adalah', o: ['Au', 'Ag', 'Fe', 'Cu'], a: 0, e: 'Berasal dari kata Latin aurum.' },
      { t: 'Partikel bermuatan negatif dalam atom adalah', o: ['elektron', 'proton', 'neutron', 'positron'], a: 0 },
      { t: 'Rumus kimia air adalah', o: ['H₂O', 'HO₂', 'H₂O₂', 'OH'], a: 0 },
      { t: 'Zat yang mempercepat reaksi tanpa ikut habis bereaksi disebut', o: ['katalis', 'reaktan', 'produk', 'pelarut'], a: 0 },
      { t: 'Nilai pH larutan netral adalah', o: ['7', '0', '14', '1'], a: 0 },
      { t: 'Unsur dengan nomor atom 6 adalah', o: ['karbon', 'nitrogen', 'oksigen', 'boron'], a: 0 },
      { t: 'Ikatan yang terbentuk karena pemakaian bersama pasangan elektron disebut ikatan', o: ['kovalen', 'ion', 'logam', 'hidrogen'], a: 0 },
      { t: 'Perubahan wujud dari padat langsung menjadi gas disebut', o: ['menyublim', 'menguap', 'mengembun', 'membeku'], a: 0 },
      { t: 'Gas yang paling banyak menyusun atmosfer bumi adalah', o: ['nitrogen', 'oksigen', 'karbon dioksida', 'argon'], a: 0, e: 'Sekitar 78% atmosfer adalah nitrogen.' },
      { t: 'Larutan dengan pH 3 bersifat', o: ['asam', 'basa', 'netral', 'amfoter'], a: 0 },
      { t: 'Rumus kimia garam dapur adalah', o: ['NaCl', 'KCl', 'NaOH', 'HCl'], a: 0 },
      { t: 'Jumlah proton dalam atom menentukan', o: ['nomor atom', 'nomor massa', 'jumlah neutron', 'massa jenis'], a: 0 },
      { t: 'Zat tunggal yang tidak dapat diuraikan lagi secara kimia disebut', o: ['unsur', 'senyawa', 'campuran', 'larutan'], a: 0 },
      { t: 'Logam yang berwujud cair pada suhu ruang adalah', o: ['raksa', 'timah', 'seng', 'natrium'], a: 0 },
      { t: 'Reaksi yang menyerap kalor dari lingkungan disebut reaksi', o: ['endoterm', 'eksoterm', 'redoks', 'netralisasi'], a: 0 },
      { t: 'Kertas lakmus merah akan berubah menjadi biru jika dicelupkan ke dalam larutan', o: ['basa', 'asam', 'netral', 'garam'], a: 0 },
      { t: 'Rumus kimia karbon dioksida adalah', o: ['CO₂', 'CO', 'C₂O', 'CaO'], a: 0 },
      { t: 'Campuran yang komponennya tidak dapat dibedakan secara kasat mata disebut campuran', o: ['homogen', 'heterogen', 'suspensi', 'koloid'], a: 0 },
      { t: 'Bilangan Avogadro bernilai sekitar', o: ['6,02 × 10²³', '6,02 × 10²²', '3,14 × 10²³', '1,6 × 10⁻¹⁹'], a: 0 },
      { t: 'Unsur golongan gas mulia bersifat', o: ['sangat stabil dan sukar bereaksi', 'sangat reaktif', 'mudah terbakar', 'bersifat asam kuat'], a: 0 },
      { t: 'Proses pemisahan campuran berdasarkan perbedaan titik didih disebut', o: ['distilasi', 'filtrasi', 'kromatografi', 'sublimasi'], a: 0 },
      { t: 'Massa atom relatif oksigen mendekati', o: ['16', '8', '32', '12'], a: 0 },
      { t: 'Zat yang melarutkan zat lain dalam suatu larutan disebut', o: ['pelarut', 'zat terlarut', 'endapan', 'residu'], a: 0 },
      { t: 'Karat pada besi terbentuk akibat reaksi dengan', o: ['oksigen dan air', 'nitrogen', 'karbon', 'hidrogen'], a: 0 },
      { t: 'Ion yang bermuatan positif disebut', o: ['kation', 'anion', 'radikal', 'isotop'], a: 0 },
      { t: 'Atom-atom dengan nomor atom sama tetapi nomor massa berbeda disebut', o: ['isotop', 'isobar', 'isoton', 'isomer'], a: 0 },
    ],
  },
  {
    id: 'biologi-dasar',
    title: 'Biologi: Sel, Tubuh, dan Ekosistem',
    category: 'Biologi',
    description: 'Struktur sel, sistem organ manusia, klasifikasi makhluk hidup, dan ekologi.',
    questions: [
      { t: 'Bagian sel yang berperan sebagai pusat pengatur kegiatan sel adalah', o: ['inti sel', 'membran sel', 'sitoplasma', 'ribosom'], a: 0 },
      { t: 'Organel yang dikenal sebagai penghasil energi sel adalah', o: ['mitokondria', 'ribosom', 'lisosom', 'vakuola'], a: 0 },
      { t: 'Proses tumbuhan membuat makanan sendiri disebut', o: ['fotosintesis', 'respirasi', 'transpirasi', 'fermentasi'], a: 0 },
      { t: 'Zat hijau daun yang menyerap cahaya matahari adalah', o: ['klorofil', 'kloroplas', 'karoten', 'xilem'], a: 0 },
      { t: 'Organ yang berfungsi memompa darah ke seluruh tubuh adalah', o: ['jantung', 'paru-paru', 'ginjal', 'hati'], a: 0 },
      { t: 'Pembuluh darah yang membawa darah keluar dari jantung disebut', o: ['arteri', 'vena', 'kapiler', 'limfa'], a: 0 },
      { t: 'Pertukaran oksigen dan karbon dioksida di paru-paru terjadi di', o: ['alveolus', 'bronkus', 'trakea', 'laring'], a: 0 },
      { t: 'Satuan terkecil makhluk hidup adalah', o: ['sel', 'jaringan', 'organ', 'molekul'], a: 0 },
      { t: 'Organ utama sistem ekskresi yang menyaring darah adalah', o: ['ginjal', 'hati', 'usus', 'limpa'], a: 0 },
      { t: 'Tumbuhan yang berkembang biak dengan spora adalah', o: ['paku', 'mangga', 'padi', 'jagung'], a: 0 },
      { t: 'Hewan yang menyusui anaknya termasuk kelompok', o: ['mamalia', 'reptil', 'amfibi', 'aves'], a: 0 },
      { t: 'Rantai makanan selalu dimulai dari', o: ['produsen', 'konsumen tingkat I', 'pengurai', 'karnivora'], a: 0 },
      { t: 'Organisme yang menguraikan sisa makhluk hidup disebut', o: ['dekomposer', 'produsen', 'herbivora', 'predator'], a: 0 },
      { t: 'Bagian bunga yang berfungsi sebagai alat kelamin betina adalah', o: ['putik', 'benang sari', 'mahkota', 'kelopak'], a: 0 },
      { t: 'Enzim yang mencerna protein di lambung adalah', o: ['pepsin', 'amilase', 'lipase', 'ptialin'], a: 0 },
      { t: 'Penyakit akibat kekurangan vitamin C adalah', o: ['skorbut', 'rakitis', 'beri-beri', 'rabun senja'], a: 0 },
      { t: 'Jaringan pengangkut air dan mineral pada tumbuhan adalah', o: ['xilem', 'floem', 'kambium', 'epidermis'], a: 0 },
      { t: 'Tulang yang melindungi otak adalah', o: ['tengkorak', 'rusuk', 'belikat', 'selangka'], a: 0 },
      { t: 'Proses perubahan bentuk sempurna pada kupu-kupu disebut', o: ['metamorfosis sempurna', 'metamorfosis tidak sempurna', 'regenerasi', 'mutasi'], a: 0 },
      { t: 'Bagian mata yang mengatur banyaknya cahaya yang masuk adalah', o: ['iris', 'kornea', 'retina', 'lensa'], a: 0 },
      { t: 'Makhluk hidup yang dapat membuat makanan sendiri disebut', o: ['autotrof', 'heterotrof', 'saprofit', 'parasit'], a: 0 },
      { t: 'Golongan darah yang dikenal sebagai donor universal adalah', o: ['O', 'AB', 'A', 'B'], a: 0 },
      { t: 'Hubungan dua makhluk hidup yang saling menguntungkan disebut', o: ['simbiosis mutualisme', 'komensalisme', 'parasitisme', 'kompetisi'], a: 0 },
      { t: 'Bagian sel tumbuhan yang tidak dimiliki sel hewan adalah', o: ['dinding sel', 'inti sel', 'mitokondria', 'membran sel'], a: 0 },
      { t: 'Pembawa sifat keturunan pada makhluk hidup adalah', o: ['gen', 'enzim', 'hormon', 'protein'], a: 0 },
      { t: 'Sistem saraf pusat terdiri atas', o: ['otak dan sumsum tulang belakang', 'otak dan jantung', 'saraf tepi dan otot', 'otak dan panca indera'], a: 0 },
    ],
  },
];
