/**
 * db/seed-data/sosial.mjs — bank soal rumpun sosial dan kebangsaan.
 *
 * Tanggal, nama, dan angka di sini sengaja dipilih yang sudah mapan di
 * buku pelajaran, bukan yang masih diperdebatkan, supaya kunci
 * jawabannya tidak berubah tergantung sumber yang dipakai guru.
 */

export const sosial = [
  {
    id: 'sejarah-indonesia',
    title: 'Sejarah Indonesia: Dari Kerajaan sampai Reformasi',
    category: 'Sejarah',
    description: 'Perjalanan bangsa dari masa kerajaan, penjajahan, kemerdekaan, hingga era reformasi.',
    questions: [
      { t: 'Proklamasi Kemerdekaan Indonesia dibacakan pada tanggal', o: ['17 Agustus 1945', '17 Agustus 1949', '1 Juni 1945', '28 Oktober 1928'], a: 0 },
      { t: 'Teks proklamasi dibacakan oleh', o: ['Soekarno', 'Mohammad Hatta', 'Sutan Sjahrir', 'Ahmad Soebardjo'], a: 0 },
      { t: 'Kerajaan Hindu tertua di Indonesia adalah', o: ['Kutai', 'Majapahit', 'Sriwijaya', 'Mataram'], a: 0, e: 'Dibuktikan lewat prasasti yupa di Kalimantan Timur.' },
      { t: 'Kerajaan maritim yang menguasai jalur perdagangan Selat Malaka pada abad ke-7 adalah', o: ['Sriwijaya', 'Majapahit', 'Singasari', 'Demak'], a: 0 },
      { t: 'Patih Majapahit yang mengucapkan Sumpah Palapa adalah', o: ['Gajah Mada', 'Hayam Wuruk', 'Raden Wijaya', 'Ken Arok'], a: 0 },
      { t: 'Sumpah Pemuda diikrarkan pada tanggal', o: ['28 Oktober 1928', '20 Mei 1908', '17 Agustus 1945', '1 Juni 1945'], a: 0 },
      { t: 'Organisasi pergerakan nasional pertama di Indonesia adalah', o: ['Budi Utomo', 'Sarekat Islam', 'Indische Partij', 'Perhimpunan Indonesia'], a: 0 },
      { t: 'Peristiwa Rengasdengklok terjadi karena golongan muda ingin', o: ['mendesak proklamasi segera dilaksanakan', 'menunda proklamasi', 'berunding dengan Jepang', 'menyerah kepada Sekutu'], a: 0 },
      { t: 'Politik Etis diterapkan Belanda dengan tiga program, yaitu irigasi, edukasi, dan', o: ['emigrasi', 'industrialisasi', 'urbanisasi', 'nasionalisasi'], a: 0 },
      { t: 'Pertempuran 10 November 1945 terjadi di kota', o: ['Surabaya', 'Bandung', 'Semarang', 'Medan'], a: 0 },
      { t: 'Konferensi Meja Bundar diselenggarakan di kota', o: ['Den Haag', 'Jakarta', 'Yogyakarta', 'Amsterdam'], a: 0 },
      { t: 'Sistem tanam paksa di Hindia Belanda dikenal dengan istilah', o: ['cultuurstelsel', 'devide et impera', 'rodi', 'romusha'], a: 0 },
      { t: 'Konferensi Asia Afrika tahun 1955 diselenggarakan di kota', o: ['Bandung', 'Jakarta', 'Surabaya', 'Medan'], a: 0 },
      { t: 'Presiden Soeharto mengundurkan diri pada tahun', o: ['1998', '1997', '1999', '1996'], a: 0 },
      { t: 'Pahlawan wanita asal Aceh yang memimpin perlawanan terhadap Belanda adalah', o: ['Cut Nyak Dien', 'Kartini', 'Dewi Sartika', 'Martha Christina Tiahahu'], a: 0 },
      { t: 'Badan yang dibentuk Jepang untuk mempersiapkan kemerdekaan Indonesia adalah', o: ['BPUPKI', 'PPKI', 'KNIP', 'MPRS'], a: 0 },
      { t: 'Pancasila sebagai dasar negara disahkan pada tanggal', o: ['18 Agustus 1945', '1 Juni 1945', '17 Agustus 1945', '22 Juni 1945'], a: 0 },
      { t: 'Perang Diponegoro berlangsung pada tahun', o: ['1825–1830', '1811–1816', '1873–1904', '1740–1755'], a: 0 },
      { t: 'Tokoh yang dikenal sebagai Bapak Koperasi Indonesia adalah', o: ['Mohammad Hatta', 'Soekarno', 'Ki Hajar Dewantara', 'Sutan Sjahrir'], a: 0 },
      { t: 'Candi Borobudur dibangun pada masa dinasti', o: ['Syailendra', 'Sanjaya', 'Isyana', 'Rajasa'], a: 0 },
      { t: 'Serangan Umum 1 Maret 1949 dipimpin oleh', o: ['Letkol Soeharto', 'Jenderal Sudirman', 'Bung Tomo', 'Kolonel Nasution'], a: 0 },
      { t: 'VOC dibubarkan pada tahun', o: ['1799', '1602', '1811', '1830'], a: 0 },
      { t: 'Tokoh pendidikan yang mendirikan Taman Siswa adalah', o: ['Ki Hajar Dewantara', 'Douwes Dekker', 'Cipto Mangunkusumo', 'Wahidin Sudirohusodo'], a: 0 },
      { t: 'Nama ibu kota Indonesia pada masa awal kemerdekaan sempat dipindahkan ke', o: ['Yogyakarta', 'Bandung', 'Surabaya', 'Bukittinggi'], a: 0 },
      { t: 'Perjanjian yang mengakui wilayah RI hanya meliputi Jawa, Sumatra, dan Madura adalah', o: ['Perjanjian Linggarjati', 'Perjanjian Renville', 'Perjanjian Roem-Royen', 'Konferensi Meja Bundar'], a: 0 },
      { t: 'Timor Timur resmi berpisah dari Indonesia melalui jajak pendapat pada tahun', o: ['1999', '1998', '2002', '1976'], a: 0 },
    ],
  },
  {
    id: 'geografi-indonesia',
    title: 'Geografi Indonesia dan Dunia',
    category: 'Geografi',
    description: 'Peta, iklim, kependudukan, sumber daya alam, dan bentang alam.',
    questions: [
      { t: 'Indonesia terletak di antara dua samudra, yaitu', o: ['Hindia dan Pasifik', 'Atlantik dan Hindia', 'Pasifik dan Arktik', 'Atlantik dan Pasifik'], a: 0 },
      { t: 'Gunung tertinggi di Pulau Jawa adalah', o: ['Semeru', 'Merapi', 'Slamet', 'Bromo'], a: 0 },
      { t: 'Ibu kota provinsi Sulawesi Selatan adalah', o: ['Makassar', 'Manado', 'Palu', 'Kendari'], a: 0 },
      { t: 'Danau terluas di Indonesia adalah', o: ['Danau Toba', 'Danau Singkarak', 'Danau Sentani', 'Danau Poso'], a: 0 },
      { t: 'Garis khayal yang membagi bumi menjadi belahan utara dan selatan adalah', o: ['khatulistiwa', 'meridian', 'bujur', 'tropis'], a: 0 },
      { t: 'Indonesia memiliki iklim', o: ['tropis', 'subtropis', 'sedang', 'kutub'], a: 0 },
      { t: 'Selat yang memisahkan Pulau Sumatra dan Jawa adalah', o: ['Selat Sunda', 'Selat Malaka', 'Selat Bali', 'Selat Makassar'], a: 0 },
      { t: 'Provinsi paling timur di Indonesia adalah', o: ['Papua', 'Maluku', 'Nusa Tenggara Timur', 'Sulawesi Utara'], a: 0 },
      { t: 'Jenis tanah yang paling subur untuk pertanian karena berasal dari abu vulkanik adalah', o: ['andosol', 'gambut', 'laterit', 'pasir'], a: 0 },
      { t: 'Sungai terpanjang di Indonesia adalah', o: ['Kapuas', 'Musi', 'Bengawan Solo', 'Mahakam'], a: 0 },
      { t: 'Angin muson barat di Indonesia membawa', o: ['musim hujan', 'musim kemarau', 'suhu dingin', 'badai salju'], a: 0 },
      { t: 'Benua terluas di dunia adalah', o: ['Asia', 'Afrika', 'Amerika', 'Eropa'], a: 0 },
      { t: 'Wilayah Indonesia terbagi menjadi berapa zona waktu?', o: ['tiga', 'dua', 'empat', 'satu'], a: 0 },
      { t: 'Alat untuk mengukur kekuatan gempa adalah', o: ['seismograf', 'barometer', 'higrometer', 'anemometer'], a: 0 },
      { t: 'Indonesia rawan gempa karena terletak pada pertemuan', o: ['tiga lempeng tektonik', 'dua samudra', 'garis khatulistiwa', 'dua benua'], a: 0 },
      { t: 'Hutan bakau banyak dijumpai di daerah', o: ['pesisir pantai', 'pegunungan', 'dataran tinggi', 'gurun'], a: 0 },
      { t: 'Negara dengan jumlah penduduk terbanyak di dunia saat ini adalah', o: ['India', 'Tiongkok', 'Amerika Serikat', 'Indonesia'], a: 0 },
      { t: 'Garis Wallace memisahkan wilayah fauna', o: ['Asiatis dan peralihan', 'Australis dan Asiatis', 'peralihan dan Australis', 'darat dan laut'], a: 0 },
      { t: 'Peta yang menggambarkan ketinggian permukaan bumi disebut peta', o: ['topografi', 'tematik', 'politik', 'navigasi'], a: 0 },
      { t: 'Ibu kota negara Australia adalah', o: ['Canberra', 'Sydney', 'Melbourne', 'Perth'], a: 0 },
      { t: 'Perpindahan penduduk dari desa ke kota disebut', o: ['urbanisasi', 'transmigrasi', 'emigrasi', 'imigrasi'], a: 0 },
      { t: 'Sumber daya alam yang dapat diperbarui adalah', o: ['air', 'minyak bumi', 'batu bara', 'emas'], a: 0 },
      { t: 'Puncak Jaya terletak di provinsi', o: ['Papua Tengah', 'Papua Barat', 'Maluku', 'Nusa Tenggara Timur'], a: 0 },
      { t: 'Laut yang terletak di antara Kalimantan dan Sulawesi adalah', o: ['Selat Makassar', 'Laut Jawa', 'Laut Banda', 'Laut Arafura'], a: 0 },
      { t: 'Fenomena naiknya permukaan air laut akibat pemanasan global disebabkan oleh', o: ['mencairnya es kutub', 'gempa bumi', 'angin topan', 'gerhana bulan'], a: 0 },
      { t: 'Negara ASEAN yang tidak memiliki wilayah laut adalah', o: ['Laos', 'Kamboja', 'Myanmar', 'Vietnam'], a: 0 },
    ],
  },
  {
    id: 'ppkn-kewarganegaraan',
    title: 'PPKn: Pancasila, UUD, dan Kewarganegaraan',
    category: 'PPKn',
    description: 'Dasar negara, konstitusi, lembaga negara, hak dan kewajiban warga negara.',
    questions: [
      { t: 'Sila pertama Pancasila berbunyi', o: ['Ketuhanan Yang Maha Esa', 'Kemanusiaan yang adil dan beradab', 'Persatuan Indonesia', 'Keadilan sosial bagi seluruh rakyat Indonesia'], a: 0 },
      { t: 'Lambang sila kelima Pancasila adalah', o: ['padi dan kapas', 'rantai', 'pohon beringin', 'kepala banteng'], a: 0 },
      { t: 'Undang-Undang Dasar 1945 disahkan pada tanggal', o: ['18 Agustus 1945', '17 Agustus 1945', '1 Juni 1945', '22 Juni 1945'], a: 0 },
      { t: 'Lembaga yang berwenang mengubah dan menetapkan UUD adalah', o: ['MPR', 'DPR', 'MA', 'Presiden'], a: 0 },
      { t: 'Semboyan negara Indonesia adalah', o: ['Bhinneka Tunggal Ika', 'Tut Wuri Handayani', 'Jalesveva Jayamahe', 'Rawe-rawe rantas'], a: 0 },
      { t: 'Lembaga yang menguji undang-undang terhadap UUD adalah', o: ['Mahkamah Konstitusi', 'Mahkamah Agung', 'Komisi Yudisial', 'DPR'], a: 0 },
      { t: 'Masa jabatan Presiden Republik Indonesia adalah', o: ['lima tahun', 'empat tahun', 'enam tahun', 'tujuh tahun'], a: 0 },
      { t: 'Hak untuk memilih dalam pemilihan umum termasuk hak', o: ['politik', 'ekonomi', 'sosial', 'budaya'], a: 0 },
      { t: 'Pancasila sebagai dasar negara tercantum dalam', o: ['Pembukaan UUD 1945 alinea keempat', 'Batang tubuh UUD pasal 1', 'Penjelasan UUD', 'Ketetapan MPR'], a: 0 },
      { t: 'Lembaga yang bertugas mengawasi penggunaan keuangan negara adalah', o: ['BPK', 'BPKP', 'KPK', 'DPD'], a: 0 },
      { t: 'Kewajiban utama warga negara terhadap hukum adalah', o: ['menaati peraturan yang berlaku', 'membayar denda', 'menjadi pejabat', 'ikut demonstrasi'], a: 0 },
      { t: 'Sistem pemerintahan Indonesia adalah', o: ['presidensial', 'parlementer', 'monarki', 'federal'], a: 0 },
      { t: 'Bendera negara Indonesia berwarna', o: ['merah dan putih', 'merah dan biru', 'putih dan biru', 'merah dan kuning'], a: 0 },
      { t: 'Bahasa persatuan bangsa Indonesia adalah', o: ['bahasa Indonesia', 'bahasa Melayu', 'bahasa Jawa', 'bahasa daerah'], a: 0 },
      { t: 'Musyawarah untuk mencapai mufakat merupakan pengamalan sila ke-', o: ['empat', 'tiga', 'dua', 'lima'], a: 0 },
      { t: 'Hak asasi manusia bersifat', o: ['melekat sejak lahir', 'diberikan pemerintah', 'dapat dijual', 'hanya untuk dewasa'], a: 0 },
      { t: 'Lembaga negara yang membuat undang-undang bersama presiden adalah', o: ['DPR', 'MPR', 'MA', 'BPK'], a: 0 },
      { t: 'Pemilihan umum di Indonesia dilaksanakan secara', o: ['langsung, umum, bebas, rahasia, jujur, dan adil', 'tertutup dan terbatas', 'bertahap dan bersyarat', 'perwakilan penuh'], a: 0 },
      { t: 'Norma yang bersumber dari hati nurani manusia disebut norma', o: ['kesusilaan', 'hukum', 'agama', 'kesopanan'], a: 0 },
      { t: 'Otonomi daerah bertujuan untuk', o: ['mendekatkan pelayanan kepada masyarakat', 'memisahkan diri dari negara', 'memperbesar pajak', 'mengurangi jumlah provinsi'], a: 0 },
      { t: 'Wakil daerah di tingkat pusat yang dipilih rakyat tiap provinsi duduk di', o: ['DPD', 'DPR', 'MPR', 'DPRD'], a: 0 },
      { t: 'Sikap menghargai perbedaan suku dan agama merupakan wujud dari', o: ['toleransi', 'apatisme', 'fanatisme', 'individualisme'], a: 0 },
      { t: 'Kekuasaan kehakiman di Indonesia dijalankan oleh', o: ['Mahkamah Agung dan badan peradilan di bawahnya', 'DPR', 'Presiden', 'Kepolisian'], a: 0 },
      { t: 'Lagu kebangsaan Indonesia diciptakan oleh', o: ['W.R. Supratman', 'Ismail Marzuki', 'C. Simanjuntak', 'Kusbini'], a: 0 },
      { t: 'Bela negara merupakan hak sekaligus', o: ['kewajiban setiap warga negara', 'pilihan bebas', 'tugas tentara saja', 'urusan pemerintah'], a: 0 },
      { t: 'Bentuk negara Indonesia menurut UUD 1945 adalah', o: ['kesatuan', 'serikat', 'federasi', 'konfederasi'], a: 0 },
    ],
  },
  {
    id: 'ekonomi-dasar',
    title: 'Ekonomi dan Literasi Keuangan',
    category: 'Ekonomi',
    description: 'Konsep dasar ekonomi, pasar, uang, perbankan, dan pengelolaan keuangan pribadi.',
    questions: [
      { t: 'Ilmu ekonomi mempelajari cara manusia memenuhi kebutuhan yang tidak terbatas dengan', o: ['sumber daya yang terbatas', 'uang yang banyak', 'teknologi canggih', 'tenaga kerja murah'], a: 0 },
      { t: 'Kegiatan menyalurkan barang dari produsen ke konsumen disebut', o: ['distribusi', 'produksi', 'konsumsi', 'promosi'], a: 0 },
      { t: 'Jika permintaan naik sedangkan penawaran tetap, maka harga cenderung', o: ['naik', 'turun', 'tetap', 'hilang'], a: 0 },
      { t: 'Lembaga yang berwenang mencetak uang rupiah adalah', o: ['Bank Indonesia', 'Bank Mandiri', 'OJK', 'Kementerian Keuangan'], a: 0 },
      { t: 'Kenaikan harga barang secara umum dan terus-menerus disebut', o: ['inflasi', 'deflasi', 'resesi', 'devaluasi'], a: 0 },
      { t: 'Badan usaha yang modalnya terbagi atas saham disebut', o: ['perseroan terbatas', 'firma', 'CV', 'koperasi'], a: 0 },
      { t: 'Kebutuhan yang harus dipenuhi agar manusia dapat hidup layak disebut kebutuhan', o: ['primer', 'sekunder', 'tersier', 'rohani'], a: 0 },
      { t: 'Pasar tempat penjual dan pembeli bertemu langsung disebut pasar', o: ['konkret', 'abstrak', 'modal', 'berjangka'], a: 0 },
      { t: 'Fungsi asli uang adalah sebagai alat tukar dan', o: ['satuan hitung', 'penimbun kekayaan', 'pembayaran utang', 'alat spekulasi'], a: 0 },
      { t: 'Lembaga yang mengawasi jasa keuangan di Indonesia adalah', o: ['OJK', 'BPK', 'KPK', 'BPS'], a: 0 },
      { t: 'Pendapatan yang diterima setelah dikurangi pengeluaran disebut', o: ['pendapatan bersih', 'pendapatan kotor', 'laba ditahan', 'modal awal'], a: 0 },
      { t: 'Menabung sebaiknya dilakukan', o: ['di awal setelah menerima pendapatan', 'setelah semua uang terpakai', 'hanya saat ada sisa', 'sekali setahun'], a: 0 },
      { t: 'Koperasi di Indonesia berlandaskan asas', o: ['kekeluargaan', 'persaingan', 'kapitalisme', 'monopoli'], a: 0 },
      { t: 'Barang yang jumlahnya terbatas dan perlu pengorbanan untuk memperolehnya disebut barang', o: ['ekonomi', 'bebas', 'ilith', 'substitusi'], a: 0 },
      { t: 'Contoh barang substitusi adalah', o: ['beras dan jagung', 'mobil dan bensin', 'kopi dan gula', 'roti dan mentega'], a: 0 },
      { t: 'Kegiatan menambah nilai guna suatu barang disebut', o: ['produksi', 'distribusi', 'konsumsi', 'reklamasi'], a: 0 },
      { t: 'Pajak yang dibebankan atas penghasilan seseorang disebut', o: ['PPh', 'PPN', 'PBB', 'bea masuk'], a: 0 },
      { t: 'Sistem ekonomi yang dianut Indonesia adalah', o: ['ekonomi Pancasila', 'liberal', 'komando', 'sosialis murni'], a: 0 },
      { t: 'Bunga yang dihitung hanya dari pokok pinjaman disebut bunga', o: ['tunggal', 'majemuk', 'efektif', 'anuitas'], a: 0 },
      { t: 'Investasi dengan risiko paling rendah pada umumnya adalah', o: ['deposito', 'saham', 'kripto', 'valuta asing'], a: 0 },
      { t: 'Neraca perdagangan surplus terjadi bila', o: ['ekspor lebih besar dari impor', 'impor lebih besar dari ekspor', 'ekspor sama dengan impor', 'tidak ada perdagangan'], a: 0 },
      { t: 'Orang yang menjalankan dan menanggung risiko usaha disebut', o: ['wirausaha', 'karyawan', 'investor pasif', 'konsumen'], a: 0 },
      { t: 'Dana darurat idealnya disiapkan sebesar', o: ['tiga sampai enam kali pengeluaran bulanan', 'satu kali gaji', 'sepuluh persen tabungan', 'tidak perlu disiapkan'], a: 0 },
      { t: 'Kegiatan menggunakan barang untuk memenuhi kebutuhan disebut', o: ['konsumsi', 'produksi', 'distribusi', 'investasi'], a: 0 },
      { t: 'Harga yang terbentuk dari pertemuan permintaan dan penawaran disebut harga', o: ['keseimbangan', 'eceran', 'pokok', 'jual'], a: 0 },
      { t: 'Menuliskan pemasukan dan pengeluaran secara rutin disebut', o: ['pencatatan anggaran', 'audit', 'akuisisi', 'likuidasi'], a: 0 },
    ],
  },
];
