/**
 * db/seed-data/umum.mjs — teknologi, literasi digital, dan pengetahuan umum.
 *
 * Bagian keamanan siber sengaja dibuat berbasis kebiasaan, bukan
 * hafalan istilah. Soal seperti "apa yang harus dilakukan ketika
 * menerima tautan yang meminta kata sandi" lebih berguna di kelas
 * daripada meminta peserta menghafal singkatan protokol.
 */

export const umum = [
  {
    id: 'informatika',
    title: 'Informatika dan Berpikir Komputasional',
    category: 'Teknologi',
    description: 'Perangkat keras, perangkat lunak, algoritma, jaringan, dan dasar pemrograman.',
    questions: [
      { t: 'Otak dari sebuah komputer yang memproses instruksi disebut', o: ['CPU', 'RAM', 'GPU', 'SSD'], a: 0 },
      { t: 'Perangkat yang termasuk masukan (input) adalah', o: ['papan ketik', 'monitor', 'pengeras suara', 'pencetak'], a: 0 },
      { t: 'Memori yang isinya hilang saat komputer dimatikan adalah', o: ['RAM', 'ROM', 'hard disk', 'flash disk'], a: 0 },
      { t: 'Satu byte terdiri atas berapa bit?', o: ['8', '4', '16', '32'], a: 0 },
      { t: 'Sistem bilangan yang digunakan komputer secara internal adalah', o: ['biner', 'desimal', 'oktal', 'romawi'], a: 0 },
      { t: 'Langkah-langkah terurut untuk menyelesaikan masalah disebut', o: ['algoritma', 'sintaks', 'kompilasi', 'variabel'], a: 0 },
      { t: 'Bahasa markah yang digunakan untuk menyusun halaman web adalah', o: ['HTML', 'Python', 'SQL', 'JSON'], a: 0 },
      { t: 'Perangkat lunak yang mengelola seluruh sumber daya komputer disebut', o: ['sistem operasi', 'peramban', 'pengolah kata', 'antivirus'], a: 0 },
      { t: 'Alamat unik setiap perangkat dalam jaringan disebut', o: ['alamat IP', 'URL', 'DNS', 'HTTP'], a: 0 },
      { t: 'Struktur data yang bekerja dengan prinsip masuk terakhir keluar pertama adalah', o: ['tumpukan (stack)', 'antrean (queue)', 'senarai', 'pohon'], a: 0 },
      { t: 'Perulangan dalam pemrograman digunakan untuk', o: ['menjalankan perintah berkali-kali', 'menyimpan data', 'menghapus berkas', 'mencetak dokumen'], a: 0 },
      { t: 'Basis data relasional menyimpan data dalam bentuk', o: ['tabel', 'gambar', 'video', 'grafik'], a: 0 },
      { t: 'Perintah SQL untuk mengambil data adalah', o: ['SELECT', 'INSERT', 'DELETE', 'UPDATE'], a: 0 },
      { t: 'Kepanjangan dari WWW adalah', o: ['World Wide Web', 'World Web Wide', 'Wide World Web', 'Web World Wide'], a: 0 },
      { t: 'Berkas dengan ekstensi .jpg merupakan berkas', o: ['gambar', 'suara', 'video', 'dokumen'], a: 0 },
      { t: 'Proses mengubah kode program menjadi bahasa mesin disebut', o: ['kompilasi', 'iterasi', 'enkripsi', 'kompresi'], a: 0 },
      { t: 'Tipe data untuk menyimpan nilai benar atau salah adalah', o: ['boolean', 'integer', 'string', 'float'], a: 0 },
      { t: 'Perangkat yang menghubungkan beberapa jaringan berbeda disebut', o: ['router', 'monitor', 'scanner', 'proyektor'], a: 0 },
      { t: 'Cloud computing berarti menyimpan dan mengolah data', o: ['di server melalui internet', 'di dalam RAM', 'di kertas', 'di CD'], a: 0 },
      { t: 'Kecerdasan buatan yang belajar dari data disebut', o: ['pembelajaran mesin', 'basis data', 'sistem operasi', 'kompilator'], a: 0 },
      { t: 'Menguraikan masalah besar menjadi bagian kecil disebut', o: ['dekomposisi', 'abstraksi', 'iterasi', 'rekursi'], a: 0 },
      { t: 'Protokol yang digunakan untuk mengirim surel adalah', o: ['SMTP', 'HTTP', 'FTP', 'SSH'], a: 0 },
      { t: 'Fungsi yang memanggil dirinya sendiri disebut', o: ['rekursif', 'iteratif', 'statis', 'global'], a: 0 },
      { t: 'Satuan penyimpanan yang setara dengan 1.024 megabyte adalah', o: ['gigabyte', 'terabyte', 'kilobyte', 'petabyte'], a: 0 },
      { t: 'Perangkat lunak sumber terbuka berarti kodenya', o: ['dapat dilihat dan dimodifikasi siapa saja', 'hanya milik satu perusahaan', 'tidak bisa diubah', 'selalu berbayar'], a: 0 },
      { t: 'Pengurutan data dari kecil ke besar disebut', o: ['ascending', 'descending', 'random', 'filtering'], a: 0 },
    ],
  },
  {
    id: 'keamanan-siber',
    title: 'Keamanan Siber dan Literasi Digital',
    category: 'Teknologi',
    description: 'Kebiasaan aman berinternet, mengenali penipuan daring, dan menjaga data pribadi.',
    questions: [
      { t: 'Kata sandi yang kuat sebaiknya', o: ['panjang dan tidak dipakai di layanan lain', 'pendek agar mudah diingat', 'sama untuk semua akun', 'berupa tanggal lahir'], a: 0 },
      { t: 'Upaya penipuan lewat pesan atau surel palsu untuk mencuri data disebut', o: ['phishing', 'caching', 'hosting', 'routing'], a: 0 },
      { t: 'Jika menerima tautan yang meminta memasukkan kata sandi bank, sebaiknya', o: ['abaikan dan buka situs resminya sendiri', 'segera klik dan isi', 'teruskan ke teman', 'balas dengan data diri'], a: 0 },
      { t: 'Verifikasi dua langkah menambah keamanan karena', o: ['penyerang butuh lebih dari sekadar kata sandi', 'kata sandi jadi lebih panjang', 'akun jadi tersembunyi', 'internet jadi lebih cepat'], a: 0 },
      { t: 'Ikon gembok pada peramban menandakan', o: ['sambungan ke situs itu terenkripsi', 'situs itu pasti aman dan jujur', 'situs milik pemerintah', 'situs bebas iklan'], a: 0, e: 'Gembok hanya menjamin sambungannya terenkripsi, bukan menjamin niat pemilik situsnya.' },
      { t: 'Perangkat lunak berbahaya yang mengunci berkas lalu meminta tebusan disebut', o: ['ransomware', 'adware', 'firewall', 'browser'], a: 0 },
      { t: 'Data pribadi yang sebaiknya tidak dibagikan di media sosial adalah', o: ['nomor induk kependudukan', 'hobi', 'kota asal', 'makanan favorit'], a: 0 },
      { t: 'Menggunakan wifi publik untuk transaksi perbankan sebaiknya', o: ['dihindari', 'selalu dilakukan', 'dianjurkan', 'tidak masalah'], a: 0 },
      { t: 'Pembaruan perangkat lunak penting dilakukan karena', o: ['menambal celah keamanan yang ditemukan', 'membuat tampilan lebih bagus', 'menghemat baterai', 'menambah penyimpanan'], a: 0 },
      { t: 'Rekayasa sosial dalam keamanan siber berarti', o: ['memanipulasi orang agar membocorkan informasi', 'membobol server', 'menulis virus', 'menyadap kabel'], a: 0 },
      { t: 'Cadangan data sebaiknya disimpan', o: ['di tempat terpisah dari perangkat utama', 'di folder yang sama', 'di memori sementara', 'tidak perlu dibuat'], a: 0 },
      { t: 'Aplikasi sebaiknya diunduh dari', o: ['toko aplikasi resmi', 'tautan di grup pesan', 'situs unduhan acak', 'iklan pop-up'], a: 0 },
      { t: 'Enkripsi berfungsi untuk', o: ['mengacak data agar hanya terbaca pihak berwenang', 'mempercepat internet', 'memperbesar berkas', 'menghapus data'], a: 0 },
      { t: 'Jejak digital adalah', o: ['rekam aktivitas yang tertinggal saat kita menggunakan internet', 'kabel jaringan', 'riwayat pembelian saja', 'nama pengguna'], a: 0 },
      { t: 'Menerima permintaan pertemanan dari akun tak dikenal sebaiknya', o: ['diperiksa dulu keasliannya', 'langsung diterima', 'langsung dibalas data diri', 'diteruskan ke teman'], a: 0 },
      { t: 'Perangkat lunak yang menyaring lalu lintas jaringan disebut', o: ['firewall', 'compiler', 'driver', 'plugin'], a: 0 },
      { t: 'Berita bohong sebaiknya diperiksa dengan cara', o: ['mencari sumber resmi dan membandingkan', 'langsung membagikannya', 'melihat jumlah suka', 'percaya pada judulnya'], a: 0 },
      { t: 'Menyimpan kata sandi di dalam pengelola kata sandi lebih aman daripada', o: ['menuliskannya di catatan ponsel tanpa kunci', 'mengingatnya', 'menggunakan dua langkah', 'mengganti berkala'], a: 0 },
      { t: 'Hak cipta atas karya digital berarti', o: ['karya tidak boleh dipakai tanpa izin pembuatnya', 'karya bebas disalin', 'karya milik penyedia layanan', 'karya otomatis milik publik'], a: 0 },
      { t: 'Perundungan yang terjadi di dunia maya disebut', o: ['perundungan siber', 'peretasan', 'penyadapan', 'spamming'], a: 0 },
      { t: 'Tanda situs palsu yang paling sering muncul adalah', o: ['alamat situs yang mirip tapi salah eja', 'warna latar gelap', 'tulisan besar', 'banyak gambar'], a: 0 },
      { t: 'Ketika akun media sosial diretas, langkah pertama adalah', o: ['mengganti kata sandi dan mengaktifkan verifikasi dua langkah', 'membuat akun baru', 'membiarkannya', 'mengumumkan ke publik'], a: 0 },
      { t: 'Izin aplikasi yang meminta akses tidak wajar sebaiknya', o: ['ditolak', 'selalu diberikan', 'diabaikan', 'diteruskan'], a: 0 },
      { t: 'Prinsip hak akses seminimal mungkin berarti', o: ['seseorang hanya diberi akses yang benar-benar ia butuhkan', 'semua orang jadi admin', 'akses dibuka penuh', 'tidak ada yang punya akses'], a: 0 },
      { t: 'Kode OTP yang dikirim ke ponsel sebaiknya', o: ['tidak pernah diberikan kepada siapa pun', 'dibagikan ke petugas bank', 'ditulis di media sosial', 'dikirim ke teman'], a: 0 },
      { t: 'Menutup sesi (logout) di komputer umum penting agar', o: ['orang berikutnya tidak bisa memakai akun kita', 'komputer lebih cepat', 'data tersimpan', 'layar mati'], a: 0 },
    ],
  },
  {
    id: 'pengetahuan-umum',
    title: 'Pengetahuan Umum dan Wawasan Dunia',
    category: 'Umum',
    description: 'Serba-serbi sains populer, tokoh dunia, olahraga, seni, dan fakta menarik.',
    questions: [
      { t: 'Planet terbesar di tata surya adalah', o: ['Jupiter', 'Saturnus', 'Bumi', 'Neptunus'], a: 0 },
      { t: 'Satelit alami bumi adalah', o: ['Bulan', 'Mars', 'Venus', 'Titan'], a: 0 },
      { t: 'Organ tubuh manusia yang paling luas permukaannya adalah', o: ['kulit', 'paru-paru', 'usus', 'hati'], a: 0 },
      { t: 'Mata uang negara Jepang adalah', o: ['yen', 'won', 'yuan', 'baht'], a: 0 },
      { t: 'Penemu bola lampu pijar yang dikenal luas adalah', o: ['Thomas Alva Edison', 'Isaac Newton', 'Albert Einstein', 'Nikola Tesla'], a: 0 },
      { t: 'Olahraga yang menggunakan raket dan kok adalah', o: ['bulu tangkis', 'tenis', 'squash', 'voli'], a: 0 },
      { t: 'Jumlah pemain dalam satu regu sepak bola di lapangan adalah', o: ['11', '10', '12', '9'], a: 0 },
      { t: 'Gunung tertinggi di dunia adalah', o: ['Everest', 'K2', 'Kilimanjaro', 'Fuji'], a: 0 },
      { t: 'Alat musik angklung berasal dari daerah', o: ['Jawa Barat', 'Bali', 'Sumatra Utara', 'Sulawesi'], a: 0 },
      { t: 'Warna yang dihasilkan dari campuran biru dan kuning adalah', o: ['hijau', 'ungu', 'jingga', 'cokelat'], a: 0 },
      { t: 'Hewan tercepat di darat adalah', o: ['cheetah', 'kuda', 'singa', 'rusa'], a: 0 },
      { t: 'Ibu kota negara Jepang adalah', o: ['Tokyo', 'Osaka', 'Kyoto', 'Nagoya'], a: 0 },
      { t: 'Alat untuk melihat benda yang sangat kecil adalah', o: ['mikroskop', 'teleskop', 'periskop', 'stetoskop'], a: 0 },
      { t: 'Piala Dunia sepak bola diselenggarakan setiap', o: ['empat tahun', 'dua tahun', 'tiga tahun', 'lima tahun'], a: 0 },
      { t: 'Benua yang tidak memiliki penduduk asli tetap adalah', o: ['Antartika', 'Australia', 'Afrika', 'Amerika Selatan'], a: 0 },
      { t: 'Tarian tradisional Saman berasal dari', o: ['Aceh', 'Bali', 'Papua', 'Jawa Tengah'], a: 0 },
      { t: 'Bahasa yang paling banyak digunakan sebagai bahasa ibu di dunia adalah', o: ['Mandarin', 'Inggris', 'Spanyol', 'Hindi'], a: 0 },
      { t: 'Instrumen musik gamelan dimainkan dengan cara', o: ['dipukul', 'ditiup', 'digesek', 'dipetik'], a: 0 },
      { t: 'Candi Prambanan merupakan candi bercorak', o: ['Hindu', 'Buddha', 'Islam', 'Kristen'], a: 0 },
      { t: 'Zat yang paling banyak menyusun tubuh manusia adalah', o: ['air', 'protein', 'lemak', 'kalsium'], a: 0 },
      { t: 'Olahraga bulu tangkis pertama kali dipertandingkan di Olimpiade pada tahun', o: ['1992', '1988', '1996', '1984'], a: 0 },
      { t: 'Batik Indonesia diakui UNESCO sebagai warisan budaya takbenda pada tahun', o: ['2009', '2005', '2012', '2015'], a: 0 },
      { t: 'Hewan yang bernapas dengan insang adalah', o: ['ikan', 'burung', 'kucing', 'ular'], a: 0 },
      { t: 'Rumah adat Joglo berasal dari daerah', o: ['Jawa Tengah', 'Sumatra Barat', 'Kalimantan', 'Sulawesi Selatan'], a: 0 },
      { t: 'Alat untuk menunjukkan arah mata angin adalah', o: ['kompas', 'jam', 'penggaris', 'timbangan'], a: 0 },
      { t: 'Lapisan atmosfer yang melindungi bumi dari sinar ultraviolet adalah', o: ['ozon', 'troposfer', 'ionosfer', 'eksosfer'], a: 0 },
    ],
  },
];
